### ISSUE TITLE
illegal base64 data at input byte 1

### ISSUE THREAD

**Issue by mAch17** [SetuHQ/setu-python-sdk#4]
When I use the scheme_id/jwt_secret copied from the dashboard as Python strings, I get this error. What is the right way to pass these parameters as String ? 
Exception: ('Bad credentials', {'code': 'jwt-verification-failed', 'detail': 'illegal base64 data at input byte 1', 'docURL': '', 'title': 'AUTHENTICATION_ERROR', 'errors': [], 'traceID':

**Comment by akshaybhalotia** [comment]
Hi @mAch17 

Using the SDK as prescribed doesn't yield in any such errors, I tried reproducing it but couldn't.

Here is how I am using the SDK after setting up a new venv and installing only Setu module:
```python
from setu import deeplink

if __name__ == "__main__":
    dl = deeplink.Deeplink(
        "<scheme_id>",
        "<secret>",
        "<merchant_id>",
        mode="SANDBOX"
    )

    link = dl.create_payment_link(
        amountValue=100,
        amountExactness="EXACT",
        billerBillID="test-bill"
    )
    print("create_payment_link", link)

    status = dl.check_payment_status(
        platformBillID=link["data"]["platformBillID"]
    )
    print("check_payment_status", status)

    mock = dl.trigger_mock_payment(
        amountValue=1.00,
        upiID=link["data"]["paymentLink"]["upiID"]
    )
    print("trigger_mock_payment", mock)

    status = dl.check_payment_status(
        platformBillID=link["data"]["platformBillID"]
    )
    print("check_payment_status", status)
```

The above worked perfectly fine and I was able to go through all the stages of payment generation, mock success and check status.
Could you show your code once to be able to help reproduce and debug this issue?

**Comment by akshaybhalotia** [comment]
#5 should fix this, could you test and let me know? If fixed, please feel free to close the issue.

**Comment by mAch17** [comment]
Yes. This works (Y).
