### ISSUE TITLE
Remove python path from settings.json

### ISSUE THREAD

**Issue by arjunattam** [SetuHQ/setu-python-sdk#6]
Hi, folks! I noticed that the `.vscode/settings.json` hard-codes a path from @nithinkashyapn's machine :). Would be nice to remove that. Here are some [best practices](https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control) to manage settings.json with version control.

**Comment by nithinkashyapn** [comment]
Hey, this has been corrected. A patch update will be rolled out shortly.
